### ISSUE TITLE
def vs defs/catvrs

### ISSUE THREAD

**Issue by DanielPuthawala** [ga4gh/cat-vrs#18]
Is the defs/catvrs folder fulfilling any practical purpose (separate from the def folder) or is it a holdover from some previous state of the repo and can be deleted?

**Comment by larrybabb** [comment]
@DanielPuthawala Is this still an issue?  There is currently only a `../schema/catvrs/def` folder, so maybe this has been resolved. Please verify and clarify otherwise please feel free to close this issue.

**Comment by DanielPuthawala** [comment]
@larrybabb It looks like this was fixed on the 1.x branch, but not the issue-14 branch, so I'm assuming that when we eventually merge issue-14 back into 1.x, that will stay fixed, right?

**Comment by DanielPuthawala** [comment]
This was fixed in 1.x branch.  Pulled that into the Issue-14 branch.
