### ISSUE TITLE
add more examples for current models

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/cat-vrs#25]
Currently there is only an example for `ProteinSequenceConsequence`. I am working on creating pydantic models for cat-vrs in https://github.com/ga4gh/cat-vrs-python and it would be nice to have examples for the other models to use in tests.

**Comment by DanielPuthawala** [comment]
You mean [in the examples here](https://github.com/ga4gh/cat-vrs/tree/617a9026232b64ddf4af4d66c778f6e452fec042/examples)?

**Comment by korikuzma** [comment]
Yes, it'd be nice to have more examples of other models!

**Comment by DanielPuthawala** [comment]
Agreed.  We're working on this, but at the same time the conversion to the constraint model is going to necessitate reworking even that example a bit...   How soon did you want this and how much/many did you want?

**Comment by korikuzma** [comment]
It's not urgent. It'd be nice to have at least 1 example for each model.

**Comment by DanielPuthawala** [comment]
I think I can safely say you will get them!

**Comment by korikuzma** [comment]
This will be handled in #87
