### ISSUE TITLE
remove commented out code in catvrs-source.yaml

### ISSUE THREAD

**Issue by korikuzma** [ga4gh/cat-vrs#26]
catvrs-source.yaml contains a significant amount of commented out code and I think it should be deleted.

[This](https://github.com/ga4gh/cat-vrs/blob/617a9026232b64ddf4af4d66c778f6e452fec042/schema/catvrs/catvrs-source.yaml#L178-L220) is not necessary to leave in and I _think_ it was just for testing?

There are also places, such as [this](https://github.com/ga4gh/cat-vrs/blob/617a9026232b64ddf4af4d66c778f6e452fec042/schema/catvrs/catvrs-source.yaml#L296-L331), where we _might_ need it later. In these situations, it's not always clear why code is commented out or what changes need to be made in order for it to be uncommented out.

I am proposing to remove out commented code to help keep our codebase clean. If there are places where code is commented out that we might need later, I would suggest creating an issue for it to address later.

**Comment by DanielPuthawala** [comment]
Makes sense.  Will add this to my to-do!

**Comment by DanielPuthawala** [comment]
Yea, those comments have already been removed in the Issue-14 branch, so that will get resolved when this branch is merged back into 1.x
