### ISSUE TITLE
Resize images on index page

### ISSUE THREAD

**Issue by DanielPuthawala** [ga4gh/cat-vrs#4]
Resize images on index page

**Comment by manish0kuniyal** [comment]
Hi there

May I kindly ask for more details on the desired dimensions or aspect ratio for the resized images on the index page? Additionally, is the reference to these images made in the ``index.rst``  file?

![image](https://github.com/ga4gh/cat-vrs/assets/110035752/dfa71cb7-0149-4dbb-a3f7-e80b18f0a2ab)

**Comment by DanielPuthawala** [comment]
Hi there Manish,

The images are referenced in the index.rst page.  I'm not sure how I want them scaled, I just noticed that some of the figures are much smaller (in terms of pixel size) than the others, but all the images are scaled to text width, which makes the last couple comically gigantic.  I sort of just want them scaled so that the elements (eg text) of the figures remain a reasonable size.  I haven't put much thought in as to how to do that in any neat or elegant way.

**Comment by manish0kuniyal** [comment]
To address this, I'd like to suggest making all the images a similar size  (maybe doing something like this **adding a  ``:width:`` attribute to set a maximum width**) to ensure the readability of text and other elements. If it's acceptable to you, may I take on this task? Once completed, you can review and adjust as needed.

**Comment by DanielPuthawala** [comment]
Sure, have at it!

**Comment by manish0kuniyal** [comment]
I've made some adjustments to the image sizes on the index page, as we discussed earlier. The changes are now available for your consideration in the PR. Please feel free to let me know if there's anything else I can do.

**Comment by DanielPuthawala** [comment]
Looks great! Thanks for fixing that!
