### ISSUE TITLE
Collect examples to seed a Test Case Driven approach to the Specification

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/cat-vrs#5]
Everyone can add links and descriptions to categorical variations here until there is a better place.

The aim of this issue is to collect examples and begin identifying the cases that we want to use as Test Cases for driving the early version of the specification. New cases can always be added at any time and the group can determine how to prioritize the work based on the resources and time commitment available by the group.

Please use [this google doc](https://docs.google.com/document/d/1aV-SqxdmuRN_EKvafzTSe0GoGC9yOzPsjrdWE0LXqYc/edit) to add more examples and comment on other's... We will close this ticket after we have a sufficient set and begin formalizing our test cases.

**Comment by larrybabb** [comment]
I'll start with a canonical representation of a simple genomic substitution and all it's derivative forms (aka ClinVar, and many of CIViC and other knowledge base representations). [NM_000410.4(HFE):c.187C>G (p.His63Asp)](https://www.ncbi.nlm.nih.gov/clinvar/variation/10/?oq=10&m=NM_000410.4(HFE):c.187C%3EG%20(p.His63Asp))

**Comment by ahwagner** [comment]
This issue should be resolved by adding a link to this document on the repo frontpage (README.md)

**Comment by DanielPuthawala** [comment]
Agreed.  Done!

**Comment by DanielPuthawala** [comment]
Agreed.  Done!
