### ISSUE TITLE
Constraint name consistancy

### ISSUE THREAD

**Issue by DanielPuthawala** [ga4gh/cat-vrs#66]
Should we drop the word `Constraint` from constraint names a la `DefiningAlleleContext` and `DefiningLocationContext` or are those constraints special for some reason?

Then update schema to reflect this decision.

**Comment by larrybabb** [comment]
We are leaving `Constraint` suffixes on subclassed `Constraint`s.  We started to add different terms like `Context` but that wasn't any better.  We also began removing `Constraint` from the subclasses altogether but we could come up with a better name for `copyConstraint` so it seemed prudent to just leave `Constraint` on the end of all subclassed `Constraint`s

**Comment by larrybabb** [comment]
Closing this for the 1.0 version unless others thing it's worth re-opening.
